# Generated by Django 5.2 on 2025-05-07 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('handedness', models.CharField(choices=[('LEFT', 'Left Handed'), ('RIGHT', 'Right Handed')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('SET1', 'Single Set'), ('SET3', 'Best of 3 Sets'), ('MTB3', 'Best of 3 Sets (Match Tiebreak in 3rd)'), ('SET5', 'Best of 5 Sets'), ('FAST4', 'Fast4')], max_length=10)),
                ('players', models.ManyToManyField(related_name='matches', to='headsup.player')),
                ('serving_first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_served_first', to='headsup.player')),
            ],
        ),
    ]
