# Generated by Django 5.2 on 2025-05-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headsup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bh_handedness',
            field=models.CharField(blank=True, choices=[('ONE', 'One Handed'), ('TWO', 'Two Handed')], max_length=3),
        ),
        migrations.AddField(
            model_name='player',
            name='fh_handedness',
            field=models.CharField(blank=True, choices=[('ONE', 'One Handed'), ('TWO', 'Two Handed')], max_length=3),
        ),
    ]
