# Generated by Django 5.2 on 2025-05-08 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headsup', '0002_player_bh_handedness_player_fh_handedness'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_lost', to='headsup.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('ABANDONED', 'Match Abdandoned'), ('COMPLETE', 'Completed'), ('INPROGRESS', 'In-Progress')], default='INPROGRESS', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_won', to='headsup.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='bh_handedness',
            field=models.CharField(choices=[('ONE', 'One Handed'), ('TWO', 'Two Handed')], max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='fh_handedness',
            field=models.CharField(choices=[('ONE', 'One Handed'), ('TWO', 'Two Handed')], max_length=3),
        ),
    ]
