# Generated by Django 5.2 on 2025-05-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headsup', '0003_match_loser_match_status_match_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(related_name='matches_played', to='headsup.player'),
        ),
    ]
