# Generated by Django 5.2 on 2025-05-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headsup', '0007_alter_match_loser_alter_match_winner_game_point_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='set',
        ),
        migrations.RemoveField(
            model_name='point',
            name='game',
        ),
        migrations.RemoveField(
            model_name='set',
            name='match',
        ),
        migrations.AddField(
            model_name='game',
            name='points',
            field=models.ManyToManyField(related_name='game_points', to='headsup.point'),
        ),
        migrations.AddField(
            model_name='match',
            name='set_scores',
            field=models.ManyToManyField(related_name='match_sets', to='headsup.set'),
        ),
        migrations.AddField(
            model_name='set',
            name='game_scores',
            field=models.ManyToManyField(related_name='set_games', to='headsup.game'),
        ),
    ]
