# Generated by Django 5.2 on 2025-05-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(default='ERROR_MISSING_TITLE', max_length=50),
        ),
    ]
