# Generated by Django 5.2 on 2025-05-16 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_question_voters_question_voters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='choices_voted_on', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='questions_voted_on', to=settings.AUTH_USER_MODEL),
        ),
    ]
