# Generated by Django 5.2 on 2025-05-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_choice_voters_alter_question_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='date_chosen',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
