# Generated by Django 5.2 on 2025-05-19 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_question_ranked_choice_ranking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='ranked_choices',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranked_choices', to=settings.AUTH_USER_MODEL),
        ),
    ]
