# Generated by Django 5.2 on 2025-05-22 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_ranking_ranked_choices_alter_ranking_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(max_length=50)),
                ('issue_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.issue')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('issue', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('voters', models.ManyToManyField(blank=True, related_name='monthly_choices_voted_on', to=settings.AUTH_USER_MODEL)),
                ('vote_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.monthlyvote')),
            ],
        ),
    ]
