# Generated by Django 5.2 on 2025-05-08 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headsup', '0005_match_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.CharField(default='Australian Open', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
