# Generated by Django 5.2 on 2025-05-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headsup', '0008_remove_game_set_remove_point_game_remove_set_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='format',
            field=models.IntegerField(choices=[(1, 'Single Set'), (3, 'Best of 3 Sets'), (3, 'Best of 3 Sets (Match Tiebreak in 3rd)'), (5, 'Best of 5 Sets')], max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='set_scores',
            field=models.ManyToManyField(blank=True, null=True, related_name='match_sets', to='headsup.set'),
        ),
    ]
