# Generated by Django 5.2 on 2025-05-12 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headsup', '0009_alter_match_format_alter_match_set_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='game_scores',
        ),
        migrations.RemoveField(
            model_name='point',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='match',
            name='set_scores',
        ),
        migrations.AddField(
            model_name='set',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='set_scores', to='headsup.match'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='player1_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='player2_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='format',
            field=models.IntegerField(choices=[(1, 'Single Set'), (3, 'Best of 3 Sets'), (5, 'Best of 5 Sets')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('ABANDONED', 'Match Abandoned'), ('COMPLETE', 'Completed'), ('INPROGRESS', 'In-Progress')], default='INPROGRESS', max_length=10),
        ),
        migrations.AlterField(
            model_name='set',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='set',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='headsup.player'),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
